<?php

class CurlFetcher {
    public function readUrl(string $url): bool|string
    {
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

        $headers = array();
        $headers[] = 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0';
        $headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8';
        $headers[] = 'Accept-Language: en-US,en;q=0.5';
        $headers[] = 'Accept-Encoding: gzip, deflate, br';
        $headers[] = 'Connection: keep-alive';
        $headers[] = 'Cookie: csrftoken=x3P5fATfcqIeOveWUAMM3S5osODTW5u1lguHjEWkfjILsaihBm3r1vghZ9yeWcMW; sessionid=.eJyNkctu2kAUQL8FS9nV1rztYYexQ8ojJAViYGPNjMc2FAh4bCYk6r_XlCzaRdXurnTP0T3S_XBS0dRl2hhdpaUwpdN1YLw-7RJgVvryIrfnYNUsC7qqfIISRtTMd744RhuzeT2km6zlMScB0JlymcC-SxDErsSYukIxBCTMc6VF6_x26JfW7XYXs_jb16gdGKKcIvQnJYX6rg9XdJfvPaulZ631xPFovCvkfe69RWXCT7T1j01lWkVzynNAA4QCqiBnAcgYFhDiAEpGKGdUyhxTHzHE_YByH3JEIAOE8VaiFHDcDgR3BAAdAIsoxLPCL1mP3RcuGHWAh7yjhuY5r93HJK338bCHlmMxtl4Tzqf7OXjMovHIZs2J5fm5X06WW7POHojqb9b7rIrOT8uiuAabW7DMCMqkJpwQKLTIGEVAqLZIaYZyFfx38F9zp5N4WCZPfXaq-vTBxunkdVRbL97aCM8xc7eENcf3AZ3Yg-hdy-pb2WgVNlZv2OVtMJvOlL_e9IYBf9_doTAJ71_kYAAuSTV8tjZ5W9zhqFVbMa10cXv0v4qdHz8BCqu9Mg:1rc8F2:5WWRY14hgTr2W-nwBhZW4YbCMRnipfbL19lOE3UEvrc; lfmanon=0; not_first_visit=1; lpfrmo=0; X-UA-Device-Type=desktop; X-UA-Country-Code=CZ';
        $headers[] = 'Upgrade-Insecure-Requests: 1';
        $headers[] = 'Sec-Fetch-Dest: document';
        $headers[] = 'Sec-Fetch-Mode: navigate';
        $headers[] = 'Sec-Fetch-Site: none';
        $headers[] = 'Sec-Fetch-User: ?1';
        $headers[] = 'If-None-Match: W/\"66ca5c8271b78cb660d089446df33e9d\"';
        $headers[] = 'Te: trailers';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return $result;

    }

    public function fetch2(string $url): bool|string
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://www.last.fm/user/MurderMadeEasy/library/artists?date_preset=ALL');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

        $headers = array();
        $headers[] = 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0';
        $headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8';
        $headers[] = 'Accept-Language: en-US,en;q=0.5';
        $headers[] = 'Accept-Encoding: gzip, deflate, br';
        $headers[] = 'Connection: keep-alive';
        $headers[] = 'Cookie: csrftoken=x3P5fATfcqIeOveWUAMM3S5osODTW5u1lguHjEWkfjILsaihBm3r1vghZ9yeWcMW; sessionid=.eJyNkctu2kAUQL8FS9nV1rztYYexQ8ojJAViYGPNjMc2FAh4bCYk6r_XlCzaRdXurnTP0T3S_XBS0dRl2hhdpaUwpdN1YLw-7RJgVvryIrfnYNUsC7qqfIISRtTMd744RhuzeT2km6zlMScB0JlymcC-SxDErsSYukIxBCTMc6VF6_x26JfW7XYXs_jb16gdGKKcIvQnJYX6rg9XdJfvPaulZ631xPFovCvkfe69RWXCT7T1j01lWkVzynNAA4QCqiBnAcgYFhDiAEpGKGdUyhxTHzHE_YByH3JEIAOE8VaiFHDcDgR3BAAdAIsoxLPCL1mP3RcuGHWAh7yjhuY5r93HJK338bCHlmMxtl4Tzqf7OXjMovHIZs2J5fm5X06WW7POHojqb9b7rIrOT8uiuAabW7DMCMqkJpwQKLTIGEVAqLZIaYZyFfx38F9zp5N4WCZPfXaq-vTBxunkdVRbL97aCM8xc7eENcf3AZ3Yg-hdy-pb2WgVNlZv2OVtMJvOlL_e9IYBf9_doTAJ71_kYAAuSTV8tjZ5W9zhqFVbMa10cXv0v4qdHz8BCqu9Mg:1rc9zS:vNmGnoy8JbQ-iz-c59lqbZML2SkZkOa55ouUlhP-YpY; lfmanon=0; not_first_visit=1; lpfrmo=0; X-UA-Device-Type=desktop; X-UA-Country-Code=CZ';
        $headers[] = 'Upgrade-Insecure-Requests: 1';
        $headers[] = 'Sec-Fetch-Dest: document';
        $headers[] = 'Sec-Fetch-Mode: navigate';
        $headers[] = 'Sec-Fetch-Site: none';
        $headers[] = 'Sec-Fetch-User: ?1';
        $headers[] = 'If-None-Match: W/\"343a2e08e7fd7ed715d655baec71b2ed\"';
        $headers[] = 'Te: trailers';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return $result;
    }
}